import { CATEGORIES } from "@/config/categories";
import { siteConfig } from "@/config/site";
import { CONTENT_TYPE_LABELS, type StoryCluster } from "@/lib/news/types";

/**
 * schema.org structured data. CurrentWire is an aggregator: clustered stories
 * are described as ItemLists/Articles that cite the original publishers —
 * CurrentWire is never marked as the original publisher of third-party work.
 */

/**
 * Publisher logo (audit F6): a raster PNG with explicit dimensions —
 * Google's article guidance wants <=600x60 and reads a dimensionless SVG as
 * a weak signal. Generated by scripts/generate-brand-assets.mjs (Chromium
 * render, so the wordmark is real Archivo).
 *
 * These numbers are hand-maintained (the generator writes the PNG but cannot
 * edit this file), so tests/unit/publisher-logo.test.ts reads the committed
 * PNG's IHDR chunk and fails if they ever drift apart. Exported for that test
 * only. NOT an ImageResponse route: ImageResponse supports "only `ttf`, `otf`,
 * and `woff` font formats" (node_modules/next/dist/docs/01-app/
 * 03-api-reference/04-functions/image-response.md, "Behavior") and next/font
 * self-hosts Archivo as woff2, so a generated wordmark would silently fall
 * back to Arial and stop being our mark.
 */
export const PUBLISHER_LOGO = {
  "@type": "ImageObject",
  url: `${siteConfig.url}/logo-600.png`,
  width: 268,
  height: 60,
};

/**
 * Publisher reference shared by NewsArticle and the standalone page types.
 * Byte-identical to the object StoryJsonLd used to inline — hoisted so
 * /about, /methodology, /editorial-standards, /corrections, /contact and
 * /topics all name the same publisher entity instead of drifting apart.
 */
const PUBLISHER_ORGANIZATION = {
  "@type": "Organization",
  name: siteConfig.name,
  url: siteConfig.url,
  logo: PUBLISHER_LOGO,
};

/** The site a page belongs to — matches WebSiteJsonLd on the home page. */
const PART_OF_WEBSITE = {
  "@type": "WebSite",
  name: siteConfig.name,
  url: siteConfig.url,
};

function JsonLd({ data }: { data: object }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

export function OrganizationJsonLd() {
  // NewsMediaOrganization (an Organization subtype) so the editorial policy
  // pages are machine-readable E-E-A-T signals. No sameAs: social profiles
  // are not published on the site, and schema must never claim what we
  // cannot verify.
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "NewsMediaOrganization",
        name: siteConfig.name,
        url: siteConfig.url,
        description: siteConfig.description,
        email: siteConfig.contactEmail,
        logo: PUBLISHER_LOGO,
        publishingPrinciples: `${siteConfig.url}/editorial-standards`,
        correctionsPolicy: `${siteConfig.url}/corrections`,
        masthead: `${siteConfig.url}/news-desk`,
        actionableFeedbackPolicy: `${siteConfig.url}/contact`,
      }}
    />
  );
}

export function WebSiteJsonLd() {
  // No SearchAction (audit F7): robots.txt disallows /search, and schema
  // must never advertise an action crawlers are told not to fetch.
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "WebSite",
        name: siteConfig.name,
        url: siteConfig.url,
      }}
    />
  );
}

/**
 * Story page: summary NewsArticle citing the original publishers' reports.
 * Dates are never our render time: datePublished prefers the archive's
 * first_seen_at (when CurrentWire actually published the story page, passed
 * in as `datePublished`), falling back to the earliest SOURCE coverage;
 * dateModified is the latest source coverage — matching the visible
 * "Published by CurrentWire" / "First coverage" / "Latest coverage" labels.
 * Authorship is the algorithmic news desk, never a fabricated human byline.
 */
/**
 * dateModified must never precede datePublished: our publication time
 * (archive first_seen_at) is usually AFTER the sources' latest coverage
 * time, so the raw pair can be logically inverted. Clamp to published.
 */
export function clampDateModified(published: string, modified: string): string {
  const p = new Date(published).getTime();
  const m = new Date(modified).getTime();
  if (!Number.isFinite(p) || !Number.isFinite(m)) return modified;
  return m >= p ? modified : published;
}

export function StoryJsonLd({
  cluster,
  datePublished,
}: {
  cluster: StoryCluster;
  /** Archive first_seen_at ISO string; falls back to firstPublishedAt. */
  datePublished?: string;
}) {
  const storyUrl = `${siteConfig.url}/story/${cluster.slug}`;
  const image = [
    // Self-hosted card first: always available, rights always clear.
    `${storyUrl}/opengraph-image`,
    ...(cluster.imageUrl?.startsWith("https://") ? [cluster.imageUrl] : []),
  ];
  const published = datePublished ?? cluster.firstPublishedAt;
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        // Always a real NewsArticle summary page — the content type is
        // carried truthfully in NewsArticle-compatible fields below
        // (articleSection + genre), never as a fabricated schema type.
        "@type": "NewsArticle",
        headline: cluster.title,
        description: cluster.summary,
        articleSection: CATEGORIES[cluster.category].label,
        ...(cluster.contentType && cluster.contentType !== "news"
          ? { genre: CONTENT_TYPE_LABELS[cluster.contentType] }
          : {}),
        datePublished: published,
        dateModified: clampDateModified(published, cluster.lastPublishedAt),
        url: storyUrl,
        mainEntityOfPage: storyUrl,
        image,
        author: {
          "@type": "Organization",
          name: "CurrentWire News Desk",
          url: `${siteConfig.url}/news-desk`,
        },
        publishingPrinciples: `${siteConfig.url}/editorial-standards`,
        correctionsPolicy: `${siteConfig.url}/corrections`,
        isBasedOn: cluster.articles.map((a) => a.url),
        publisher: PUBLISHER_ORGANIZATION,
        about: cluster.entities.map((name) => ({ "@type": "Thing", name })),
      }}
    />
  );
}

/** Ranked list (Top 100 and section lists). */
export function ItemListJsonLd({
  clusters,
  path,
  name,
  startPosition = 1,
}: {
  clusters: StoryCluster[];
  path: string;
  name: string;
  /** Rank of the first item — paginated lists continue the ranking. */
  startPosition?: number;
}) {
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "ItemList",
        name,
        url: `${siteConfig.url}${path}`,
        numberOfItems: clusters.length,
        itemListElement: clusters.slice(0, 30).map((cluster, index) => ({
          "@type": "ListItem",
          position: startPosition + index,
          name: cluster.title,
          url: `${siteConfig.url}/story/${cluster.slug}`,
        })),
      }}
    />
  );
}

/**
 * ItemList for pages whose entries are not story clusters (the reverse-chron
 * feed, the publisher index). Same shape as ItemListJsonLd; the caller
 * supplies name/url pairs that must already be canonical, indexable URLs.
 */
export function LinkListJsonLd({
  items,
  path,
  name,
  startPosition = 1,
}: {
  items: { name: string; url: string }[];
  path: string;
  name: string;
  startPosition?: number;
}) {
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "ItemList",
        name,
        url: `${siteConfig.url}${path}`,
        numberOfItems: items.length,
        itemListElement: items.slice(0, 30).map((item, index) => ({
          "@type": "ListItem",
          position: startPosition + index,
          name: item.name,
          url: item.url.startsWith("http")
            ? item.url
            : `${siteConfig.url}${item.url}`,
        })),
      }}
    />
  );
}

export function BreadcrumbJsonLd({
  items,
}: {
  items: { name: string; path: string }[];
}) {
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: items.map((item, index) => ({
          "@type": "ListItem",
          position: index + 1,
          name: item.name,
          item: `${siteConfig.url}${item.path}`,
        })),
      }}
    />
  );
}

/**
 * Evergreen reference page (the /methodology/* explainers).
 *
 * WebPage, not Article: these pages carry no byline and no honest publication
 * date — they describe how the system works right now and are rewritten in
 * place whenever it changes, so datePublished/dateModified would be invented.
 * Never FAQPage/HowTo (playbook: they earn no rich result and invite
 * fabricated markup).
 */
export function ReferencePageJsonLd({
  name,
  description,
  path,
}: {
  name: string;
  description: string;
  path: string;
}) {
  // Same payload it always emitted, now built by trustPageSchema: a reference
  // page IS a trust page whose type happens to be the default WebPage, and two
  // near-identical builders would drift the moment one of them gained a field.
  return <JsonLd data={trustPageSchema({ name, description, path })} />;
}

/**
 * Hub page whose value is the collection itself (/topics): CollectionPage
 * wrapping an ItemList of the hub URLs.
 *
 * The caller must pass ONLY URLs that answer `index`. Topic hubs below
 * `shouldIndexCollection` are deliberately `noindex, follow`, and schema must
 * never advertise a URL that tells crawlers to stay out — the same rule
 * app/sitemap.ts already applies to this exact list.
 *
 * `numberOfItems` counts what is actually emitted, not the pre-slice total:
 * declaring 40 while listing 30 is a small lie and this site does not tell
 * them.
 */
export function collectionPageSchema({
  path,
  name,
  description,
  items,
}: {
  path: string;
  name: string;
  description: string;
  /** Already filtered to indexable URLs by the caller. */
  items: { name: string; url: string }[];
}) {
  const listed = items.slice(0, 30);
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name,
    description,
    url: `${siteConfig.url}${path}`,
    inLanguage: "en",
    isPartOf: PART_OF_WEBSITE,
    publisher: PUBLISHER_ORGANIZATION,
    mainEntity: {
      "@type": "ItemList",
      numberOfItems: listed.length,
      itemListElement: listed.map((item, index) => ({
        "@type": "ListItem",
        position: index + 1,
        name: item.name,
        url: item.url.startsWith("http")
          ? item.url
          : `${siteConfig.url}${item.url}`,
      })),
    },
  };
}

export function CollectionPageJsonLd(
  props: Parameters<typeof collectionPageSchema>[0],
) {
  return <JsonLd data={collectionPageSchema(props)} />;
}

/**
 * Trust / editorial-policy pages: /about (AboutPage), /contact (ContactPage)
 * and the policy pages (WebPage, also used by the /methodology/* reference
 * pages). These are the exact URLs OrganizationJsonLd already points at via
 * publishingPrinciples, correctionsPolicy, masthead and
 * actionableFeedbackPolicy — typing them closes the E-E-A-T loop in both
 * directions instead of leaving them as merely crawlable prose.
 *
 * Deliberately carries NO datePublished/dateModified. These pages are edited
 * in git, not published on a date the site records, so any timestamp here
 * would be invented. Guarded by tests/unit/structured-data-pages.test.ts and
 * by scripts/seo-health.mjs against the live HTML.
 */
export function trustPageSchema({
  path,
  name,
  description,
  type = "WebPage",
}: {
  path: string;
  name: string;
  description: string;
  type?: "AboutPage" | "ContactPage" | "WebPage";
}) {
  return {
    "@context": "https://schema.org",
    "@type": type,
    name,
    description,
    url: `${siteConfig.url}${path}`,
    inLanguage: "en",
    isPartOf: PART_OF_WEBSITE,
    publisher: PUBLISHER_ORGANIZATION,
  };
}

export function TrustPageJsonLd(props: Parameters<typeof trustPageSchema>[0]) {
  return <JsonLd data={trustPageSchema(props)} />;
}
